clusterName: se-360-eks-hot-site
region: ap-southeast-2
vpcId: vpc-0563c914d41dc227a

serviceAccount:
  create: false
  name: aws-load-balancer-controller
  namespace: kube-system

ingressClass: none

