apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: se-360-eks-hot-site
  region: ap-southeast-2

# Sử dụng VPC có sẵn
vpc:
  id: vpc-0563c914d41dc227a
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  subnets:
    public:
      # 3 public subnet cho Traefik/ALB
      public-subnet-1:
        id: subnet-0695792f899d93886
      public-subnet-2:
        id: subnet-066d6622d593c26f2
      public-subnet-3:
        id: subnet-02fdbce0d88a67c41
    private:
      # 3 private subnet cho NodeGroup
      private-subnet-1:
        id: subnet-00358ccf055ceba51
      private-subnet-2:
        id: subnet-052b4e056eeb84efe
      private-subnet-3:
        id: subnet-057dc5804d06344ab

# IAM OIDC cho ALB/NLB controller
iam:
  withOIDC: true

# NodeGroup chạy trong private subnet
nodeGroups:
  - name: ng-main-new
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 6
    privateNetworking: true
    availabilityZones:
      - ap-southeast-2a
      - ap-southeast-2b
      - ap-southeast-2c

# chú thích:
# - NodeGroup trong private subnet
# - LoadBalancer (NLB/ALB) trong public subnet
